#!/bin/bash

execdir=$(dirname $0)
basename=$(basename $0)
. $execdir/../conf.d/$basename.conf

[ -z "$BASEDIR" ] && BASEDIR=$HOME

for gitdir in $(find $BASEDIR -name '.git' -type d)
do
    curdate=$(date "+%F %H:%M:%S")
    workdir=$(dirname $gitdir)
    basename=$(basename $workdir)
    cd $workdir
    git fetch > /dev/null 2>&1 || echo "!c $curdate <$LOGNAME> !c $workdir warn: git fetch yield errors"
    git branch -avvvv 2>&1 | grep -q ': ahead ' && echo "!c $curdate <$LOGNAME> !c $workdir warn: local commits in the repository"
    git log -v --since="$1" --until="$2" --date=iso8601 | perl -e '$_=do {  local $/ = <> }; @foo=split(/^commit/m); for $commit (@foo) { @lines=split(/\n/m, $commit); next if $lines[1] !~ /[Tt]obi/; $lines[2] =~ /Date:\s*(.*) [+-]/; print "$1 <'$LOGNAME'> !c '$basename' $lines[4]\n"; } '
done
